DATABASE_HOST=localhost;
DATABASE_NAME=spring_security;
DATABASE_PASSWORD=1234;
DATABASE_PORT=3306;
DATABASE_USER=root;

JWT_EXPIRATION=86400000;
JWT_ISSUER=yulikelion;
JWT_SECRET=NiOeyFbN1Gqo10bPgUyTFsRMkJpGLXSvGP04eFqj5B30r5TcrtlSXfQ7TndvYjNvfkEKLqILn0j1SmKODO1Yw3JpBBgI3nVPEahqxeY8qbPSFGyzyEVxnl4AQcrnVneI